### ISSUE TITLE
Does not camelize keys of nested objects

### ISSUE THREAD

**Issue by katmug** [sindresorhus/camelcase-keys#1]
camelcaseKeys() works perfectly fine for a flat json object. However, the keys of nested json objects wont camelize.

ex: //works fine for
{
  'foo-bar': true,
  'foo bar2': true,
  'foo_bar_foo': true,
}

ex 2: //Doesn't  work for 
{ 
      'foo-bar': true,
      'nested.foo':
       {
	    'foo-bar': true,
	    'foo bar2': true,
	    'foo_bar_foo': true
	}
}

//ex 2: Output  
{ fooBar: true,
  nestedFoo: { 'foo-bar': true, 'foo bar2': true, foo_bar_foo: true } }

**Comment by sindresorhus** [comment]
Yes, it's not recursive.

**Comment by LinusU** [comment]
@sindresorhus Would you be open to a `{ deep: true }` or `{ recursive: true }` option?

related: dsblv/decamelize-keys#1

**Comment by kevva** [comment]
```js
const camelcaseKeys = require('camelcase-keys');
const mapObj = require('map-obj');

const camelize = obj => camelcaseKeys(mapObj(obj, (key, val) => typeof val === 'object' ? [key, camelize(val)] : [key, val]));

camelize({'foo-key': 'bar', 'obj-key': {'obj-bar': 'foo'}});
//=> {fooKey: 'bar', objKey: {objBar: 'foo'}}
```

**Comment by sindresorhus** [comment]
@LinusU Out of scope for this module. I would never need something like that and deep comes with a lot of unforeseen complications.

**Comment by LinusU** [comment]
Faire enough, I could publish another package 👌

**Comment by rxaviers** [comment]
@sindresorhus, first of all great work with this library. As usual, great libraries...

For the ones that need deep support: https://github.com/rxaviers/camelcase-keys-deep
