### ISSUE TITLE
Trying to use this lib with Nest.js, and getting import error

### ISSUE THREAD

**Issue by sebpowell** [sindresorhus/camelcase-keys#100]
I'm trying to use this library in Nest.js, in the following way:

```
import camelcaseKeys from 'camelcase-keys';
```

When I do this, Nest.js gives me the following message:

```
const camelcase_keys_1 = require("camelcase-keys");
                         ^
Error [ERR_REQUIRE_ESM]: require() of ES Module 
Instead change the require of index.js in ... which is available in all CommonJS modules.
```

As far as I can tell, no require statements are used anywhere, so I'm not sure whether it's something I'm doing wrong?

Any help would be greatly appreciated.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
