### ISSUE TITLE
iOS archive failed - phasescriptexecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by suhailpahmin** [sindresorhus/camelcase-keys#105]
Getting this error during iOS archive
`Command PhaseScriptExecution failed with a nonzero exit code`

caused by this line in camelcase-keys index.js
`const cache = new QuickLru({maxSize: 100_000});`

I have to change 100_000 to 100000 for it to archive successfully. But this gonna fail on CI/CD pipeline

**Comment by sindresorhus** [comment]
This is not a problem with this package.
