### ISSUE TITLE
Failed import camelcase-keys

### ISSUE THREAD

**Issue by tangcent** [sindresorhus/camelcase-keys#107]
error:
```
Error: require() of ES Module /app/available_modules/1669777001000/camelcase-keys/index.js from /app/index.js not supported.
Instead change the require of /app/available_modules/1669777001000/camelcase-keys/index.js in /app/index.js to a dynamic import() which is available in all CommonJS modules.
```
go to npm runkit: https://npm.runkit.com/camelcase-keys
run: 
```
var camelcaseKeys = require("camelcase-keys")
```
![image](https://user-images.githubusercontent.com/17569144/204699569-1c3d15f7-8b8c-415c-a1e1-d64d443a7a00.png)

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by tangcent** [comment]
@sindresorhus thank you for the reply

**Comment by sezanzeb** [comment]
Seems to work with `--experimental-require-module`
