### ISSUE TITLE
type mismatch with reality

### ISSUE THREAD

**Issue by raidenmiro** [sindresorhus/camelcase-keys#113]
If we transform an object like `{ ProjectID: '...' }`, he becomes `{ projectId: '...' }`. But by types, it becomes `projectID`.

Reproduce https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQIYgKYBs0GcMDSGAnrnAL5wBmUEIcA5AMbrYv4C0A1ibgwFD8YxMBjgAlDLgCuWeAF4UrHKnxFSAHgT84cAAq0AVhiYwAkgBEAXHFwwowAHYBzfuQB8gphEd24PLhtJGTl+AHow3SiAPQB+IA

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/camelcase-keys/issues/88
