### ISSUE TITLE
Version 9 does not recursively camelCase keys in nested objects when using union with null

### ISSUE THREAD

**Issue by yonex** [sindresorhus/camelcase-keys#118]
Hello,

I recently upgraded `camelcase-keys` from version `8.0.2` to `9.1.0` and encountered an issue where nested object keys are not being camelCased recursively when using a union type with `null`.

#### Example Code:

Here's a TypeScript example to illustrate the issue:

```typescript
type MyType = {
  foo_bar: {
    foo_prop: string;
  } | null;
};

type MyTypeCamel = CamelCaseKeys<MyType, true>;
```

In version `8.0.2`, the `MyTypeCamel` would be:

```typescript
{
  fooBar: {
    fooProp: string;
  } | null;
}
```

However, in version `9.1.0`, it becomes:

```typescript
{
  fooBar: {
    foo_prop: string;
  } | null;
}
```

It is worth noting that this issue does not occur when the nested object type is not unioned with `null`.

Is this a known issue, or is there a new configuration setting that I am not aware of? I would appreciate your assistance on this matter.

Thank you!

**Comment by sindresorhus** [comment]
// @yutak23

**Comment by yonex** [comment]
@yutak23 @sindresorhus Thank you for the prompt resolution of the issue! I've updated to version 9.1.2 in my own project and can confirm that the issue has been resolved. I really appreciate the quick turnaround.
