### ISSUE TITLE
Documentation doesn't match the types? 

### ISSUE THREAD

**Issue by jsinglamms** [sindresorhus/camelcase-keys#121]
Hello, 

looking the documentation, you say that camelcaseKeys support object or object[], right? why If I do the following code I've got an error?

```
import toCamel from 'camelcase-keys';

class SomeObject {
    someProperty!: string
}

console.log(toCamel<object>(new SomeObject()))
```

This is the error that I get:
```
 Type 'object' does not satisfy the constraint 'readonly any[] | Record<string, unknown>
```

Can you improve the documentation? or I'm doing something wrong?

Thanks!

**Comment by sindresorhus** [comment]
// @yutak23

**Comment by sindresorhus** [comment]
The API expects plain objects, not classes.
