### ISSUE TITLE
Why don't you provide cjs build?

### ISSUE THREAD

**Issue by walt1992** [sindresorhus/camelcase-keys#125]
I know nowaday almost every recent environment support ESM, So doesn't need cjs.

But, There is still many environment do not support cjs vice versa. So I think there is no reason not provider cjs build file from npm packages. 

I saw some PR that required cjs module. You just share link about ESM. But The real requirement is cjs module I think.
How do you think about it?

**Comment by sindresorhus** [comment]
Shipping both CJS and ESM comes with a lot of downsides too, so I have picked only ESM. Please read: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c?permalink_comment_id=3850849#gistcomment-3850849
