### ISSUE TITLE
Consider supporting both pure ESM and commonJS simultaneously

### ISSUE THREAD

**Issue by robgonnella** [sindresorhus/camelcase-keys#129]
I've run into an issue in a NestJS / Typescript project that is written in pure ESM but transpiled to commonJS to be served via Node 20. While I know I can rename all extensions to `.cts` and update all imports to include `.cjs` extension (annoying but doable), I ran into absolute hell getting ts-jest / jest integrations to work.  Jest / Ts-jest do not seem to support `cts` and I'm not willing to sacrifice typings in test files; hence this post. I lost too much time trying to get various configurations to work with jest. If you have a solution to this problem I'm happy to put the work in to try it out but I'm fresh out of ideas at this point. If you're open to the possibility of supporting both ESM and CommonJS I've created a commit in a fork that does just that and I'm happy to post a PR: https://github.com/robgonnella/camelcase-keys/commit/1f2fb264def9159941af18b4606745f55f5bd66a

**Comment by sindresorhus** [comment]
Sorry, not interested in bringing back CommonJS support.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
