### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by alexeikaratai** [sindresorhus/camelcase-keys#14]
$ react-scripts build
Creating an optimized production build...
Failed to compile.

static/js/main.472219b2.js from UglifyJs
Invalid assignment [./~/camelcase-keys/index.js:6,0][static/js/main.472219b2.js:18310,23]

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
