### ISSUE TITLE
Failed to minify the code from this file....

### ISSUE THREAD

**Issue by badenkov** [sindresorhus/camelcase-keys#17]
Hello!

My node version - 8.1.4
      npm version - 5.3.0
      yarn version - 0.27.5

react-scripts version 1.0.17
  
I'm using create-react-app, and works well, but when I call 

```
yarn run build
```

I've got an error:

```
yarn run v0.27.5
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/camelcase-keys/index.js:6

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There is the same error with camelcase, map-obj, and maybe somewhere else.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

I'm sorry create-react-app is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support create-react-app.
