### ISSUE TITLE
Adding camelcase-keys to Ember.js app breaks Internet Explorer 11

### ISSUE THREAD

**Issue by duncan-bayne** [sindresorhus/camelcase-keys#20]
We have an Ember 2.16 application, that loads correctly on Internet Explorer 11.  When we add `camelcase-keys`:

```diff
+++ b/frontend/package.json
@@ -29,6 +29,7 @@
     "breakpoint-sass": "^2.7.1",
     "broccoli-asset-rev": "^2.4.5",
     "broccoli-babel-transpiler": "^5.7.2",
+    "camelcase-keys": "^4.2.0",
```
... then the application fails to load, with the following error:

```
SCRIPT5009: 'define' is undefined
```

... but _only_ on IE11.  All other browsers we test against work fine.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
