### ISSUE TITLE
Don't turn nested arrays into objects with deep: true

### ISSUE THREAD

**Issue by mgol** [sindresorhus/camelcase-keys#22]
Test case (with `camelcase-keys@4.2.0`):
```js
const camelcaseKeys = require('camelcase-keys');
JSON.stringify(camelcaseKeys({
  "q_w_e": [
    [
      "a",
      "b",
    ],
  ],
}, {deep: true}), null, 4);
```
Actual result:
```js
{
    "qWE": [
        {
            "0": "a",
            "1": "b"
        },
    ],
}
```
Expected result:
```js
{
    "qWE": [
        [
            "a",
            "b",
        ],
    ],
}
```

**Comment by avinograd0v** [comment]
+1, 
I have to use Object.entries(obj).map(([key, value] => {}), which is quite unclear

**Comment by mgol** [comment]
@talyssonoc Your test case is different and doesn't have nested arrays. Try mine and you'll see the issue.

**Comment by talyssonoc** [comment]
@mgol ooh, I see! Yeah, you're right, it happens as well. Thanks for the clarification 😄
