### ISSUE TITLE
Add an `omit` option to skip some fields in the output object

### ISSUE THREAD

**Issue by kilianc** [sindresorhus/camelcase-keys#24]
This may be out of scope but I find myself doing `camelcaseKeys((omit(o, 'foo'))` a lot.
Would this considered out of scope?

**Comment by sindresorhus** [comment]
You can already do this: `camelcaseKeys(o, {excude: ['foo']}))`

**Comment by kilianc** [comment]
> exclude
>
>Type: string[] RegExp[]
>Default: []
>
>Exclude keys from being camelCased.

I meant excluding keys from the output object. Not just skipping the case change

**Comment by sindresorhus** [comment]
I see, no that's outside the scope of this module.
