### ISSUE TITLE
@types/camelcase-keys/index has no default export.

### ISSUE THREAD

**Issue by chrismooreproductions** [sindresorhus/camelcase-keys#29]
I'm having a problem with the type definitions as in the title.

Fixed by replacing `export = camelcaseKeys;` in index.d.ts to `export default camelcaseKeys` and moving below the camelcaseKeys function

**Comment by sindresorhus** [comment]
I don't control those typings. You need to open an issue on https://github.com/DefinitelyTyped/DefinitelyTyped
