### ISSUE TITLE
Doesn't convert PascalCase to camelCase correctly

### ISSUE THREAD

**Issue by johnnyoshika** [sindresorhus/camelcase-keys#3]
Example:
`camelcaseKeys({FooBar: true})`

Result:
`{ foobar: true }`

The expected behaviour:
`{ fooBar: true }`

**Comment by SamVerschueren** [comment]
Wow this is odd, it uses `camelcase` in the background which should convert it correctly. Will have a look it at.

**Comment by SamVerschueren** [comment]
This is an issue in [camelcase](https://github.com/sindresorhus/camelcase), not in `camelcase-keys`. You should create an issue over there.

I tested it, and this is indeed not handled by `camelcase`.

**Comment by SamVerschueren** [comment]
@johnnyoshika It's fixed in `v2.0.1` of `camelcase`. So just reinstall `camelcase-keys` and the issue should be resolved.

**Comment by johnnyoshika** [comment]
@SamVerschueren Fantastic!  Thank you so much.

**Comment by SamVerschueren** [comment]
Don't thank me, I was just the messenger boy here ;).

**Comment by johnnyoshika** [comment]
I just re-imported this package and everything works well now.
