### ISSUE TITLE
I created kebabcase-keys based on a fork of this package

### ISSUE THREAD

**Issue by mattiloh** [sindresorhus/camelcase-keys#31]
Hi Sindre! Thanks for sharing another neat and useful package with the world 🙏 
I needed a conversion from camelCase to kebab-case, so I forked this repo and published a package with the same API for kebab-case conversion: https://github.com/mattiloh/kebabcase-keys

I only changed the case-conversion, the rest is untouched. I'm not sure how to adjust the license file in this case, so I just didn't touch it. Please let me know, if I should change it or adjust the way I give credit to your work.

**Comment by sindresorhus** [comment]
Cool 👍 Do a PR to add it here: https://github.com/sindresorhus/camelcase-keys#related

**Comment by sindresorhus** [comment]
> I'm not sure how to adjust the license file in this case, so I just didn't touch it.

Just add your copyright here: https://github.com/mattiloh/kebabcase-keys/blob/70ab8577e1505926e836d371aa66fb7638a44d84/license#L2 while still keeping mine below.
