### ISSUE TITLE
v6 breaks on edge

### ISSUE THREAD

**Issue by dangreenisrael** [sindresorhus/camelcase-keys#40]
Since the upgrade from `v5.2=>6` this package has been broken on edge due to a lack of support for the object spread operator.

https://github.com/sindresorhus/camelcase-keys/compare/v5.2.0...v6.0.0#diff-168726dbe96b3ce427e7fedce31bb0bc

https://github.com/sindresorhus/camelcase-keys/blob/807dd95f34bf2d21c0635e7477f5dc8b599acb48/index.js#L10-L13

According to MDN, this is not supported at al by Edge
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility

As far as I can tell, this makes version 6 unsafe for web.

Would it be possible to go back to using `Object.assign` or to publish something that is Babelized for all browser?  IMO it would be onerous to expect implementers to run their node_modules through Babel.

**Comment by dangreenisrael** [comment]
@dhoffman34

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by dhoffman34** [comment]
@sindresorhus, it does not seem that it is compatible with Babel 7: https://github.com/SamVerschueren/babel-engine-plugin/issues/16

Any recommendations?
