### ISSUE TITLE
Unexpected token '...'. Expected a property name on Safari 10

### ISSUE THREAD

**Issue by maafaishal-tkpd** [sindresorhus/camelcase-keys#45]
<img width="1110" alt="Screen Shot 2019-09-25 at 12 11 25" src="https://user-images.githubusercontent.com/48900190/65571104-9f72e280-df8d-11e9-903e-9bfd191ab606.png">

This is because Safari 10 is not supported object rest spread. This module should add `@babel/plugin-transform-destructuring` plugin to Webpack to handle this error.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
