### ISSUE TITLE
Generic parameter type, breaking change

### ISSUE THREAD

**Issue by haakondr** [sindresorhus/camelcase-keys#55]
We are using camelcase-keys by passing in objects typed as interfaces, and the type check failed after upgrading to 6.0.2, related change #54, #50. Minimal example:

```
interface SomeObject {
	someProperty: string;
}

const someObj: SomeObject = {
	someProperty: "hello",
};

camelcaseKeys(someObj);
```

typescript then complains with the following:
```
  ✖  37:14  No overload matches this call.
  Overload 1 of 2, (input: readonly { [key: string]: unknown; }[], options?: Options | undefined): readonly { [key: string]: unknown; }[], gave the following error.
    Argument of type SomeObject is not assignable to parameter of type readonly { [key: string]: unknown; }[].
      Type SomeObject is missing the following properties from type readonly { [key: string]: unknown; }[]: length, concat, join, slice, and 16 more.
  Overload 2 of 2, (input: { [key: string]: unknown; }, options?: Options | undefined): { [key: string]: unknown; }, gave the following error.
    Argument of type SomeObject is not assignable to parameter of type { [key: string]: unknown; }.
      Index signature is missing in type SomeObject.  
```

I did solve this by extending my interface with the following:

```
interface CamelCasable {
	[key: string]: unknown;
}

interface SomeObject extends CamelCasable {
	someProperty: string;
}
```

This way, my interface adheres to the required parameter type in the camelcaseKeys function.  I do agree that this type check is correct. Problem is, I then have to add this to all the objects I pass in to camelcaseKeys in my project.

My question is then as follows:

- is there an alternative to make the parameter type slightly less restrictive?

something like:

```
declare function camelcaseKeys<T>(
	input: T,
	options?: camelcaseKeys.Options,
): T;
```

- Alternatively, should I reconsider my approach of using interfaces as types?

I can make a PR with code example changes, but I thought I'd start the discussion first. Not sure if this is really a problem, or me doing typescript the wrong way.

**Comment by sindresorhus** [comment]
Does it work if you change `unknown` to `any` here: https://github.com/sindresorhus/camelcase-keys/blob/f4d91c0392ff660e26f16850f101efb679c57d09/index.d.ts#L102 ?

**Comment by sindresorhus** [comment]
// @jmca

**Comment by haakondr** [comment]
Yes, that works. I made a PR #56, please let me know what you think. I cannot say I fully understand why unkown -> any does fix it though. Either way, I think the type signature really should care about whether or not we get a object or array having keys being strings (all object keys are strings, no?).

**Comment by jmca** [comment]
@haakondr I agree with you in using `any` instead of `unknown`, especially for backward compatibility and interface use.

I'll note that type errors are thrown when using `interface` over `type =`. 
`type` passes, `interface` has issues with the strictness of `unknown`.
