### ISSUE TITLE
Pascalcase option doesnt work

### ISSUE THREAD

**Issue by fhhhnasnd123** [sindresorhus/camelcase-keys#58]
I'm trying to convert camelCase to PascalCase, but this doesn't work for me. 

camelcaseKeys({fooBar: true, nested: {unicorn_rainbow: true}}, {pascalCase: true});

returns:
{fooBar: true, nested: {unicorn_rainbow: true}}

**Comment by sindresorhus** [comment]
You need to use the `deep` option too.

**Comment by fhhhnasnd123** [comment]
Still doesnt work

**Comment by sindresorhus** [comment]
Oh, I missed that. But we do have tests to confirm it should be working: https://github.com/sindresorhus/camelcase-keys/blob/147c3c25568d0e7ae5188d322fcf00e3910d9fd5/test.js#L78-L92

Make sure you are on the latest version. 

Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and I'll take a closer look.
