### ISSUE TITLE
Use recuse version of map-obj ? 

### ISSUE THREAD

**Issue by sjmcdowall** [sindresorhus/camelcase-keys#6]
Either via an option -- or -- by default (I can't imagine too many use cases where you wouldn't want this) use map-obj-recurse instead of map-obj so the whole object graph gets converted?? 

If interested I can certainly do a PR for this ..

**Comment by sindresorhus** [comment]
I can't imagine a case I *would* want this. Can you provide a realistic use-case?

**Comment by sjmcdowall** [comment]
Sure -- I receive via a REST call a legacy set of data that I want to insert in to a doc store where each key is something like  FOO_BAR  in a complex object graph.  After I run it through just camelcase-keys I have the following result below -- note how the inner object key names are still in the horrid legacy format .. don't want that..

{
"adjust": [
{
"NAME":  ""
} ,
{
"NAME":  ""
}
] ,
"axisOrder":  "XYZ" ,
"contGrp": [
{
"CONTEXTS": [ ]
} ,
{
"CONTEXTS": [ ]
}
] ,
"custUse": [ ],
"czStartId":  "05f78cd2-8100-4d52-81d7-228d34d32b84" ,
"fct":  "" ,
"fctArgs": [ ],
"id":  "5232304b-47e6-4861-b5fb-6eab857e3ade" ,
"lotId":  "UNKNOWNLOT" ,
"patGrp": [
{
"PATTERNS": [
"ti245_func_VMD.PAT"
]
} ,
{
"PATTERNS": [ ]
}
] ,
"pinGrp": [ ],
"setups": [
{
"ALGO_NAME":  "Linear" ,
"MODE":  "X Shmoo" ,
"P_NAME": [
"Open"
] ,
"P_TYPE":  "Edge" ,
"RG_FROM": [
0
] ,
"RG_STPS": 20 ,
"RG_STPSZ": [
2.75e-8
] ,
"RG_TO": [
5.5e-7
] ,
"SH_TNAME": [ ],
"SH_TTYPE": [ ],
"SPEC_UNIT":  "Time" ,
"STEP_NAME":  "X_Shmoo_Vps"
} ,
{
"ALGO_NAME":  "Linear" ,
"MODE":  "Y Shmoo" ,
"P_NAME": [
"Vps"
] ,
"P_TYPE":  "Level" ,
"RG_FROM": [
3.38
] ,
"RG_STPS": 20 ,
"RG_STPSZ": [
0.011
] ,
"RG_TO": [
3.6
] ,
"SH_TNAME": [ ],
"SH_TTYPE": [ ],
"SPEC_UNIT":  "Volt" ,
"STEP_NAME":  "Axis_1"
}
] ,
"siteCnt": 2 ,
"sublotId":  "UNKNOWNSUBLOT" ,
"testCell":  "Tester123" ,
"timeStamp":  "2016-09-16T17:02:32.252Z" ,
"tstMeth":  "Reburst" ,
"userId":  "UNKNOWN"
}

**Comment by sjmcdowall** [comment]
BTW -- if you don't think it's generally useful then I propose to add a "recurse: true/false" option to the options object (default would be NOT to recuse to keep old functionality) but then to recurse if set to true.

**Comment by sindresorhus** [comment]
Ok, sure, I have something ready offline. Will publish tomorrow.

**Comment by sjmcdowall** [comment]
Oh cool -- my great idea doesn't handle array of objects either as the PR notes (that I pulled). :)

**Comment by sjmcdowall** [comment]
Just fyi -- I implemented a mini recursive version (my boss wanted it now of course) with this code -- and it looks to work pretty slick by using the traverse() package.  Maybe a change of how the routine works maybe good? 

```
function camelcaseKeys(obj) {
    // The forEach will modify in place
    traverse(obj).forEach(function camelNode(node) {
        if (!this.isRoot) {
            this.delete();
            this.key = camelcase(this.key);
            this.update(node);
        }
    });

    return obj;
}
```

**Comment by sjmcdowall** [comment]
BTW -- works like a charm!  Woot!
