### ISSUE TITLE
decimal points in keys are stripped by camelcaseKeys

### ISSUE THREAD

**Issue by toneworm** [sindresorhus/camelcase-keys#64]
This wouldn't be my approach but I've inherited a codebase which uses floats as keys in some of the api responses. These get stripped out when using camelcaseKeys.

```
const camelcaseKeys = require('camelcase-keys');
camelcaseKeys({ 2.95: true }); // { 295: true }
```

**Comment by sindresorhus** [comment]
You can exclude such keys with the `exclude` option. It's not something that will be handled here.

**Comment by toneworm** [comment]
nice one cheers
