### ISSUE TITLE
lowercase and UPPERCASE keys are not getting converted into camelCase

### ISSUE THREAD

**Issue by Salmandabbakuti** [sindresorhus/camelcase-keys#71]
The title says it all. Here's the reproduced issue:
![Screenshot (405)](https://user-images.githubusercontent.com/29351207/115955216-e1219180-a512-11eb-836e-6f88ba0c2f34.png)

is this the expected behaviour or am I missing anything?

**Comment by sindresorhus** [comment]
Yes, that's expected behavior.
