### ISSUE TITLE
Incorrect types when using optional property with nested structure and deep option

### ISSUE THREAD

**Issue by monisnap-paul** [sindresorhus/camelcase-keys#77]
When using optional properties in a type and the option deep: true, the nested type is not properly converted to camelcase.

<img width="471" alt="Screenshot 2021-08-06 at 14 08 34" src="https://user-images.githubusercontent.com/84771357/128508234-3177a8dc-b6a5-4aca-be7e-1d6076d81b2f.png">

Here is a repository which reproduces the error. 
https://github.com/monisnap-paul/camelcase-keys-bug

**Comment by sindresorhus** [comment]
// @g-plane

**Comment by g-plane** [comment]
This may be able to be fixed, but the "optional" mark will be lost as the given example. For example:

```ts
type Source = { a?: string }
```

will become:

```ts
type Result = { a: string | undefined }
```

These are different in TypeScript.

**Comment by monisnap-paul** [comment]
There are actually two issues with the given example: 

1. "City" and "Country" properties in the type are not properly converted to camelcase
2. "?" is not equivalent to "| undefined"

**Comment by g-plane** [comment]
> "?" is not equivalent to "| undefined"

I know, but we can't operate: [TypeScript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8lC8UDeUCGB+AXFAdgVwFsAjCAJwBoojsiB7WgGwlRygF8AoUSKAJQWRQA2gGkoAS1YBrCCFoAzWAF1sMUUvZA).

**Comment by salemhilal** [comment]
I wanted to bump this. It seems like even if `{ someKey?: string}` is different than `{ someKey: string | undefined }`, that's probably a level less important than having the type be `{ some_key?: string }` but having the actual value be `{ someKey: string | undefined }`.

If that's a cool assumption to make, I'd be open to submitting a patch for this issue.

**Comment by RichiCoder1** [comment]
Ironically I think this fix for this is to use the type `CamelCasedPropertiesDeep` from `type-fest`.

**Comment by jandolezal71** [comment]
> I wanted to bump this. It seems like even if `{ someKey?: string}` is different than `{ someKey: string | undefined }`, that's probably a level less important than having the type be `{ some_key?: string }` but having the actual value be `{ someKey: string | undefined }`.
> 
> If that's a cool assumption to make, I'd be open to submitting a patch for this issue.

Output type should be `{ someKey?: string | undefined }` or `{ someKey?: string }`. 

In some cases you don't want to pass keys with undefined values explicitely.
