### ISSUE TITLE
Add ES5 version to NPM release

### ISSUE THREAD

**Issue by samageloff** [sindresorhus/camelcase-keys#8]
Hey @sindresorhus, thanks for this super-helpful utility. I'm curious if you can provide an ES5 version of `camelcase-keys` (and `camelcase`), that would reduce the need for us to transpile this in our build.

I'd be glad to submit a PR, if this is something you're open to. 

Best, 
Sam

**Comment by SamVerschueren** [comment]
We focus on Node, not tbe browser. If you want it, you have 2 valid options. Either transpile it or use [v3.0.0](https://github.com/sindresorhus/camelcase-keys/tree/v3.0.0).
