### ISSUE TITLE
Wrong result with log4j word to camel case?

### ISSUE THREAD

**Issue by emmanuelsio** [sindresorhus/camelcase-keys#82]
I have different words with log4j. The one of example is uses_log4j. 

```
var camelcaseKeys = require("camelcase-keys")
camelcaseKeys({'uses_log4j': true}); 
//=> usesLog4J

```
The result of that word should be usesLog4j ? why is making capital letter after a number?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/camelcase/issues/77
