### ISSUE TITLE
Exporting `CamelCaseKeys` transformer type 🙏🏻

### ISSUE THREAD

**Issue by prescience-data** [sindresorhus/camelcase-keys#86]
Is it possible to export the `CamelCaseKeys` type located https://github.com/sindresorhus/camelcase-keys/blob/main/index.d.ts#L39

```typescript
CamelCaseKeys<
	T extends Record<string, any> | readonly any[],
	Deep extends boolean,
	IsPascalCase extends boolean,
	Exclude extends readonly unknown[],
	StopPaths extends readonly string[],
	Path extends string = ''
>

```

It would be really handy to be able to access rather than needing to make a local copy which may get out of sync with the package.

**Comment by JoshM1994** [comment]
As they're by the same author, my solution was to separately install https://github.com/sindresorhus/type-fest

**Comment by prescience-data** [comment]
Exported via `type-fest`
