### ISSUE TITLE
`Error [ERR_REQUIRE_ESM]`: Must use import to load ES Module: `ROOT\node_modules\camelcase-keys\index.js`

### ISSUE THREAD

**Issue by farhan-shaikh-raw** [sindresorhus/camelcase-keys#93]
Getting error on `firebase deploy`. Full error below

`Error: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\node\codelabs\in_app_purchases\complete\firebase-backend\functions\node_modules\camelcase-keys\index.js                      require() of ES modules is not supported. `

> **Node Version**

`14.18.2`

> **firebase Version**

`11.1.0`

> **tsconfig.json**

`{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}`

> **Steps followed**

`https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#10`

> **Git Repo**

`https://github.com/flutter/codelabs/tree/master/in_app_purchases/complete/firebase-backend`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by simplenotezy** [comment]
@sindresorhus How would this work with Nest.js

**Comment by simplenotezy** [comment]
I ended up simply using:

```ts
_.mapKeys(obj, (v, k) => _.camelCase(k))
```

Since importing the package was not easily possible with Nest.js unfortunately

**Comment by freddygarcia** [comment]
> > I ended up simply using:
> > ```ts
> > _.mapKeys(obj, (v, k) => _.camelCase(k))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since importing the package was not easily possible with Nest.js unfortunately
> 
> What is "_" and obj here?

@GeylanKalafMohe [Lodash](https://lodash.com)

**Comment by isaachinman** [comment]
Hello all. I've created a util to convert ESM-only packages to CJS, for those who need it. This is still very much a work in progress, so please open an issue [on the repository](https://github.com/isaachinman/cjs-exporter) with any feedback.

This package (`camelcase-keys@8.0.2`) can be installed as CJS via `@cjs-exporter/camelcase-keys`.

**Comment by akay64** [comment]
I used an approach where I used ESBuild to convert this ESM only lib to CJS format should work for most of such cases. Took the result of the build and the `index.d.ts` file, put it into a "vendor" directory and import from there. Problem solved if you don't want to migrate off of CJS if your project already works that way. It took 5 to 10 mins max and got back on track.

1. `npm install esbuild`
2. git clone repo of the ESM lib you want to use that does not offer CJS support in this case to `./camelcase-keys`
3. open `package.json` of that repo
4. remove the line `"type": "module"`
5. Remove `"exports": { "types": "./index.d.ts", "default": "./index.js" }`
6. Add `"types": "./index.d.ts"` and `"main": "./index.js"`
7. `npx esbuild ./camelcase-keys --bundle --platform="node" --outfile=./static-vendor/camelcase-keys/index.js`
8. import and use in your code like normal `import camelcaseKeys from "../static-vendor/camelcase-keys/index.js";`
9. Copy `index.d.ts` file from cloned repo to `./static-vendor/camelcase-keys/`

If you want you can probably alias it or something and make the import cleaner but this is fine for my needs, typing also works perfectly.

Cheers.
